version: '3.9'
services:
  sistemacursos:
    container_name: sistemacursos
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: java_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
      MYSQL_DB: backendjava
      MYSQL_URL: jdbc:mysql://java_db/backendjava
    depends_on:
      - java_db

  java_db:
    container_name: sistemaCursosDB
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: backendjava